# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff075b13ca8582cee306975a84551ca496cc0dc2320c9a7338919b11377e53431c7171e8be3b6ce4b1fa9dc0e755d053fdfa4087b4d33ebe9c45461422621d4

test:
  secret_key_base: 1e7b0a8804685fd510f33d6d7cfc744cb8e99c7839277d8453e7d44d18db239eb10c77303c1c9e1a11b5775e3b9fcbf16e8e5de93034b41166882355a70b6bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
